# Generated by Django 4.2.5 on 2023-11-24 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILE_HASHES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_hash', models.CharField(max_length=64)),
                ('vendor', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('update', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
