# Generated by Django 4.2.5 on 2023-11-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FILE_HASHES',
        ),
    ]
