# Generated by Django 4.2.5 on 2023-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_rename_file_file_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_hashes',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
